name: Node.js CI with Docker

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: |
          cd /home/ubuntu/actions-runner/_work/node-project/node-project
          docker build -t node-app .

      - name: Remove existing container if exists
        run: |
          docker ps -a -q -f name=node-app-container | grep -q . && docker rm -f node-app-container || echo "No existing container to remove"

      - name: Run Docker container
        run: |
          cd /home/ubuntu/actions-runner/_work/node-project/node-project
          docker run -d -p 3000:3000 --name node-app-container node-app
