name: Node.js CI with Docker (Cross-Platform)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set environment variables for path (Linux)
        if: runner.os == 'Linux'
        run: echo "PROJECT_DIR=/home/ubuntu/actions-runner/_work/node-project/node-project" >> $GITHUB_ENV

      - name: Set environment variables for path (Windows)
        if: runner.os == 'Windows'
        run: echo "PROJECT_DIR=C:\Users\Arslan\Desktop\github runner\_work\node-project\node-project" >> $env:GITHUB_ENV
        shell: powershell

      - name: Build Docker image
        run: |
          echo "Building Docker image in $env:PROJECT_DIR"
          cd "$env:PROJECT_DIR"
          docker build -t node-app .
        shell: powershell

      - name: Remove existing container if exists (Windows)
        if: runner.os == 'Windows'
        shell: powershell
        run: |
          Set-ExecutionPolicy -ExecutionPolicy RemoteSigned -Scope Process -Force
          if (docker ps -a -q -f "name=node-app-container") {
            docker rm -f node-app-container
          } else {
            echo "No existing container to remove"
          }

      - name: Remove existing container if exists (Linux)
        if: runner.os == 'Linux'
        run: |
          if docker ps -a -q -f name=node-app-container | grep -q .; then
            docker rm -f node-app-container
          else
            echo "No existing container to remove"
          fi

      - name: Run Docker container (Windows)
        if: runner.os == 'Windows'
        shell: powershell
        run: |
          Set-ExecutionPolicy -ExecutionPolicy RemoteSigned -Scope Process -Force
          cd "$env:PROJECT_DIR"
          docker run -d -p 3000:3000 --name node-app-container node-app

      - name: Run Docker container (Linux)
        if: runner.os == 'Linux'
        run: |
          cd "$PROJECT_DIR"
          docker run -d -p 3000:3000 --name node-app-container node-app
