name: Node.js CI with Docker

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: |
          cd /home/ubuntu/actions-runner/_work/node-project/node-project
          docker build -t node-app .

      - name: Check npm scripts
        run: |
          cd /home/ubuntu/actions-runner/_work/node-project/node-project
          docker run --rm node-app npm run

      - name: Run build inside container
        run: |
          cd /home/ubuntu/actions-runner/_work/node-project/node-project
          docker run --rm node-app npm run build

      - name: Run tests inside container
        run: |
          cd /home/ubuntu/actions-runner/_work/node-project/node-project
          docker run --rm node-app npm test
